name: tanks
description: Otus tanks project.
version: 0.0.1
homepage: https://github.com/kirimi/otus_tanks

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  vector_math: ^2.1.1

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.0
